# -*- mode: ruby -*-
# vi: set ft=ruby :


# **** VM CONTENTS ***** 
# Modded Minecraft Server


$minecraft = <<-'SCRIPT'

  mkdir "/opt/minecraft"
  cd "/opt/minecraft"
  cp "/vagrant/forge-1.20.6-50.1.0-installer.jar" "/opt/minecraft/forge-installer.jar"

  java -jar forge-installer.jar --installServer

SCRIPT

Vagrant.configure("2") do |config|

  # start with debian box 
  config.vm.box = "debian/bookworm64"

  # networking - forward minecraft ports
  config.vm.network "forwarded_port", guest: 25565, host: 25565

  config.vm.provision "shell", inline: "apt-get update" 

  # utilities
  config.vm.provision "shell", inline: "apt-get install --yes tmux" 

  # minecraft 
  config.vm.provision "shell", inline: "sudo apt-get install --yes default-jdk" # java development kit
  config.vm.provision "shell", inline: "sudo apt-get install --yes default-jre" # java runtime
  config.vm.provision "shell", inline: $minecraft  

end
