# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # start with debian box 
  config.vm.box = "debian/bookworm64"

  # forward from main to minecraft port
  # config.vm.network "forwarded_port", guest: 25565, host: 25565

  # install server dependencies
  config.vm.provision "shell", inline: "sudo apt-get install --yes openjdk-8-jdk" # java development kit
  config.vm.provision "shell", inline: "sudo apt-get install --yes default-jre"   # java runtime
  config.vm.provision "shell", inline: "sudo apt-get install --yes "              # minecraft


end
