# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # start with debian box 
  config.vm.box = "debian/bookworm64"

  # install media-server (jellyfin)
  config.vm.provision "shell" do |s|
    s.inline = "wget https://repo.jellyfin.org/install-debuntu.sh | chmod +777 install-debuntu.sh | sudo /install-debuntu.sh | rm install-debuntu.sh"
  end
end
