# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure("2") do |config|

  # start with debian box 
  config.vm.box = "debian/bookworm64"

  # setup networking - jellyfin portforwarding 
  config.vm.network "forwarded_port", guest: 8096, host: 8096

  config.vm.provision "shell", inline: "sudo apt-get update"

  # install media-server (jellyfin)
  config.vm.provision "shell", inline: "sudo apt-get install --yes curl"
  config.vm.provision "shell", inline: "curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash"

  # install utilities
  config.vm.provision "shell", inline: "sudo apt-get install --yes tmux"

  # setup backup 
  config.vm.provision "shell", inline: "echo 'tar zcf /vagrant/backup/media.tgz ~/' | sudo tee /usr/local/bin/backup-home.sh" 
  config.vm.provision "shell", inline: "sudo chmod +x /usr/local/bin/backup-home.sh"
  config.vm.provision "shell", inline: "echo '0 5 * * * /usr/local/bin/backup-home.sh' | crontab -"

end
