# -*- mode: ruby -*-
# vi: set ft=ruby :





Vagrant.configure("2") do |config|

  # start with debian box 
  config.vm.box = "debian/bookworm64"

  # forward from main to jellyfin on box
  config.vm.network "forwarded_port", guest: 8096, host: 8096

  # install media-server (jellyfin)
  config.vm.provision "shell", inline: "sudo apt-get install --yes jellyfin"

end
