# -*- mode: ruby -*-
# vi: set ft=ruby :




Vagrant.configure("2") do |config|
  # start with debian box 
  config.vm.box = "debian/bookworm64"

  # install media-server (jellyfin)
  config.vm.provision "shell" do |s|
    s.inline = "echo hello world"
  end
end
